<?php

use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Blade;
use App\Models\User;

require __DIR__ . '/../vendor/autoload.php';
$app = require __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

// Clear compiled views so custom directives take effect
\Illuminate\Support\Facades\Artisan::call('view:clear');

// Override @script and @endscript directives for static HTML export
Blade::directive('script', function () {
    return '<?php ob_start(); ?>';
});
Blade::directive('endscript', function () {
    return '<?php $__scriptContent = ob_get_clean(); $__rawScript = preg_replace("/^\s*<script[^>]*>|<\/script>\s*$/i", "", $__scriptContent); echo "<script>document.addEventListener(\'DOMContentLoaded\', function() { " . $__rawScript . " });</script>"; ?>';
});

// Authenticate dummy user for Blade views expecting auth()->user()
$user = new User([
    'id' => 1,
    'name' => 'Yrizzz',
    'email' => 'admin@adminkit.io',
]);
Auth::setUser($user);

$distDir = __DIR__ . '/../dist';
if (File::exists($distDir)) {
    File::deleteDirectory($distDir);
}
File::makeDirectory($distDir, 0755, true);
File::makeDirectory($distDir . '/assets', 0755, true);
File::makeDirectory($distDir . '/dashboards', 0755, true);
File::makeDirectory($distDir . '/pages', 0755, true);
File::makeDirectory($distDir . '/pages/content', 0755, true);
File::makeDirectory($distDir . '/auth', 0755, true);

// 1. Copy build assets to dist/assets
$buildAssetDir = __DIR__ . '/../public/build/assets';
if (File::exists($buildAssetDir)) {
    File::copyDirectory($buildAssetDir, $distDir . '/assets');
}

// Find main CSS and JS files
$cssFile = '';
$jsFile = '';
$fontsCssFile = '';
foreach (File::files($distDir . '/assets') as $file) {
    $filename = $file->getFilename();
    if (str_starts_with($filename, 'app-') && str_ends_with($filename, '.css')) {
        $cssFile = $filename;
    }
    if (str_starts_with($filename, 'app-') && str_ends_with($filename, '.js')) {
        $jsFile = $filename;
    }
    if (str_starts_with($filename, 'fonts-') && str_ends_with($filename, '.css')) {
        $fontsCssFile = $filename;
    }
}

// Copy public icons & favicons if exist
foreach (['favicon.ico', 'favicon.svg', 'favicon-32.png', 'favicon-16.png', 'apple-touch-icon.png'] as $fav) {
    if (File::exists(__DIR__ . '/../public/' . $fav)) {
        File::copy(__DIR__ . '/../public/' . $fav, $distDir . '/' . $fav);
    }
}

echo "Assets prepared in dist/assets\n";

function getDepthPrefix($targetPath) {
    $parts = explode('/', trim($targetPath, '/'));
    $count = count($parts) - 1;
    return $count > 0 ? str_repeat('../', $count) : './';
}

function processHtmlContent($html, $targetRelativePath, $cssFile, $jsFile, $fontsCssFile) {
    $prefix = getDepthPrefix($targetRelativePath);
    
    // 1. Normalize full localhost URLs generated by Laravel route()
    $html = preg_replace('/https?:\/\/localhost(:[0-9]+)?/i', '', $html);

    // 2. Convert dynamic dashboard URLs: href="/dashboards/sales" -> href="dashboards/sales.html"
    $html = preg_replace_callback('/href=["\']\/dashboards\/([a-zA-Z0-9_\-]+)["\']/', function($matches) use ($prefix) {
        return 'href="' . $prefix . 'dashboards/' . $matches[1] . '.html"';
    }, $html);

    // 3. Convert dynamic page URLs: href="/page/docs" -> href="pages/content/docs.html"
    $html = preg_replace_callback('/href=["\']\/page\/([a-zA-Z0-9_\-\/]+)["\']/', function($matches) use ($prefix) {
        $cleanPath = str_replace('/', '-', $matches[1]);
        return 'href="' . $prefix . 'pages/content/' . $cleanPath . '.html"';
    }, $html);

    // 4. Exact route URL replacements with strict quote boundary checks
    $exactReplacements = [
        '/dashboard' => $prefix . 'index.html',
        '/ui/elements' => $prefix . 'pages/ui-elements.html',
        '/ui/icons' => $prefix . 'pages/icons.html',
        '/widgets' => $prefix . 'pages/widgets.html',
        '/tables' => $prefix . 'pages/tables.html',
        '/charts' => $prefix . 'pages/charts.html',
        '/forms' => $prefix . 'pages/forms.html',
        '/settings' => $prefix . 'pages/settings.html',
        '/apps/kanban' => $prefix . 'pages/kanban.html',
        '/docs' => $prefix . 'pages/content/docs.html',
        '/login' => $prefix . 'auth/login.html',
        '/register' => $prefix . 'auth/register.html',
        '/forgot-password' => $prefix . 'auth/forgot-password.html',
    ];

    foreach ($exactReplacements as $from => $to) {
        $html = preg_replace('/href=["\']' . preg_quote($from, '/') . '["\']/', 'href="' . $to . '"', $html);
    }
    
    // Fallback for root path
    $html = preg_replace('/href=["\']\/["\']/', 'href="' . $prefix . 'pages/content/landing.html"', $html);

    // Replace Vite asset injection with static CSS/JS references in head
    $headAssets = '';
    if ($fontsCssFile) {
        $headAssets .= '<link rel="stylesheet" href="' . $prefix . 'assets/' . $fontsCssFile . '">' . "\n";
    }
    if ($cssFile) {
        $headAssets .= '<link rel="stylesheet" href="' . $prefix . 'assets/' . $cssFile . '">' . "\n";
    }
    if ($jsFile) {
        $headAssets .= '<script src="' . $prefix . 'assets/' . $jsFile . '"></script>' . "\n";
    }
    
    // Clean up Vite development tags & injection
    $html = preg_replace('/<script type="module" src="http:\/\/localhost:[0-9]+\/@vite\/client"><\/script>/i', '', $html);
    $html = preg_replace('/<script type="module" src="[^"]+resources\/js\/app\.js"><\/script>/i', '', $html);
    $html = preg_replace('/<link rel="stylesheet" href="[^"]+resources\/css\/app\.css">/i', '', $html);
    
    // Inject generated CSS and JS assets before </head>
    $html = str_replace('</head>', $headAssets . '</head>', $html);
    
    // Clean up Livewire script/style tags & attributes
    $html = preg_replace('/<script [^>]*livewire[^>]*>.*?<\/script>/is', '', $html);
    $html = preg_replace('/<style [^>]*livewire[^>]*>.*?<\/style>/is', '', $html);
    $html = preg_replace('/wire:id="[^"]*"/', '', $html);
    $html = preg_replace('/wire:snapshot="[^"]*"/', '', $html);

    $html = preg_replace('/<meta name="csrf-token" content="[^"]*">/', '<meta name="csrf-token" content="static-html-token">', $html);

    // Inject icon rendering trigger at bottom of body
    $iconInit = '<script>document.addEventListener("DOMContentLoaded", function() { if (window.renderIcons) window.renderIcons(); });</script>';
    $html = str_replace('</body>', $iconInit . '</body>', $html);

    return $html;
}

$standalonePaths = [
    'landing',
    'docs',
    'sign-in', 'sign-in-2', 'sign-up', 'sign-up-2',
    'lock-screen', 'lock-screen-2', 'reset-password', 'reset-password-2',
    'create-password', 'two-step-verification', 'coming-soon',
    'under-maintenance', 'no-internet',
];

function renderFullPageFromView($viewName, $data = [], $title = 'Dashboard') {
    global $standalonePaths;

    $data['pageTitle'] = $data['pageTitle'] ?? $title;
    $data['subtitle'] = $data['subtitle'] ?? 'Real-time telemetries, revenue metrics & workspace activity.';
    $data['pageDesc'] = $data['pageDesc'] ?? 'Overview & activity metrics.';
    $data['breadcrumbs'] = $data['breadcrumbs'] ?? [['label' => 'Pages'], ['label' => $title]];
    $path = $data['path'] ?? 'overview';
    $data['path'] = $path;
    $data['section'] = $data['section'] ?? 'Main';

    $content = View::make($viewName, $data)->render();

    $isStandalone = in_array($path, $standalonePaths, true) 
        || str_starts_with($path, 'error-') 
        || str_starts_with($viewName, 'livewire.pages.content.sign-')
        || str_starts_with($viewName, 'livewire.pages.content.lock-')
        || str_starts_with($viewName, 'livewire.pages.content.reset-')
        || str_starts_with($viewName, 'livewire.pages.content.error-');

    $layoutName = $isStandalone ? 'components.layouts.auth' : 'components.layouts.app';

    $layout = View::make($layoutName, ['title' => $title, 'slot' => new \Illuminate\Support\HtmlString($content)])->render();
    return $layout;
}

$renderedCount = 0;

// 1. Dashboard Main -> index.html & dashboard.html
echo "Rendering Main Dashboard...\n";
$mainDashHtml = renderFullPageFromView('livewire.dashboard', [], 'Dashboard');
$processedMain = processHtmlContent($mainDashHtml, 'index.html', $cssFile, $jsFile, $fontsCssFile);
File::put($distDir . '/index.html', $processedMain);
File::put($distDir . '/dashboard.html', processHtmlContent($mainDashHtml, 'dashboard.html', $cssFile, $jsFile, $fontsCssFile));
$renderedCount += 2;

// 2. Dashboards (dashboards/*.blade.php)
$dashFiles = File::files(__DIR__ . '/../resources/views/livewire/dashboards');
foreach ($dashFiles as $file) {
    $name = str_replace('.blade.php', '', $file->getFilename());
    $title = ucfirst($name) . ' Dashboard';
    echo "Rendering Dashboard: {$name}...\n";
    try {
        $html = renderFullPageFromView('livewire.dashboards.' . $name, ['path' => $name, 'subtitle' => "Real-time {$name} telemetries and analytics."], $title);
        $processed = processHtmlContent($html, 'dashboards/' . $name . '.html', $cssFile, $jsFile, $fontsCssFile);
        File::put($distDir . '/dashboards/' . $name . '.html', $processed);
        $renderedCount++;
    } catch (\Throwable $e) {
        echo "Warning: Error rendering dashboard {$name}: " . $e->getMessage() . "\n";
    }
}

// 3. Main Livewire Pages
$pageFiles = File::files(__DIR__ . '/../resources/views/livewire/pages');
foreach ($pageFiles as $file) {
    $name = str_replace('.blade.php', '', $file->getFilename());
    $title = ucfirst(str_replace('-', ' ', $name));
    echo "Rendering Page: {$name}...\n";
    try {
        $html = renderFullPageFromView('livewire.pages.' . $name, ['path' => $name], $title);
        $processed = processHtmlContent($html, 'pages/' . $name . '.html', $cssFile, $jsFile, $fontsCssFile);
        File::put($distDir . '/pages/' . $name . '.html', $processed);
        $renderedCount++;
    } catch (\Throwable $e) {
        echo "Warning: Error rendering page {$name}: " . $e->getMessage() . "\n";
    }
}

// 4. Content pages (pages/content/*.blade.php)
$contentFiles = File::files(__DIR__ . '/../resources/views/livewire/pages/content');
foreach ($contentFiles as $file) {
    $name = str_replace('.blade.php', '', $file->getFilename());
    $title = ucfirst(str_replace('-', ' ', $name));
    echo "Rendering Content Page: {$name}...\n";
    try {
        $html = renderFullPageFromView('livewire.pages.content.' . $name, ['path' => $name], $title);
        $targetFile = 'pages/content/' . $name . '.html';
        $processed = processHtmlContent($html, $targetFile, $cssFile, $jsFile, $fontsCssFile);
        File::put($distDir . '/' . $targetFile, $processed);
        if ($name === 'landing') {
            File::put($distDir . '/landing.html', processHtmlContent($html, 'landing.html', $cssFile, $jsFile, $fontsCssFile));
        }
        if ($name === 'docs') {
            File::put($distDir . '/docs.html', processHtmlContent($html, 'docs.html', $cssFile, $jsFile, $fontsCssFile));
        }
        $renderedCount++;
    } catch (\Throwable $e) {
        echo "Warning: Error rendering content page {$name}: " . $e->getMessage() . "\n";
    }
}

// 5. Auth pages
$authViews = [
    'login' => ['view' => 'livewire.pages.content.sign-in', 'title' => 'Sign In'],
    'register' => ['view' => 'livewire.pages.content.sign-up', 'title' => 'Sign Up'],
    'forgot-password' => ['view' => 'livewire.pages.content.reset-password', 'title' => 'Reset Password'],
    'lock-screen' => ['view' => 'livewire.pages.content.lock-screen', 'title' => 'Lock Screen'],
];
foreach ($authViews as $key => $conf) {
    echo "Rendering Auth: {$key}...\n";
    try {
        if (View::exists($conf['view'])) {
            $html = renderFullPageFromView($conf['view'], ['path' => $key], $conf['title']);
            $processed = processHtmlContent($html, 'auth/' . $key . '.html', $cssFile, $jsFile, $fontsCssFile);
            File::put($distDir . '/auth/' . $key . '.html', $processed);
            $renderedCount++;
        }
    } catch (\Throwable $e) {
        echo "Warning: Error rendering auth page {$key}: " . $e->getMessage() . "\n";
    }
}

echo "\nSUCCESS! Successfully generated {$renderedCount} static HTML pages in dist/\n";
